# Generated by Django 6.0 on 2025-12-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
